### ISSUE TITLE
evm not starting at start-up

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [duydo/evm#12]
Im using macbook air 2017. iterm with zsh is default terminal
to start evm i've to to "evm start" daily and also i cant close that terminal if i close it then "evm status" shows that evm is not runnning.
Is this a normal ?

**Comment by duydo** [comment]
@Kaustubh-Natuskar Sorry for late response.
Checkout the latest release, evm should run in background.

**Comment by Kaustubh-Natuskar** [comment]
> @Kaustubh-Natuskar Sorry for late response.
> Checkout the latest release, evm should run in background.

No problem will checkout the new release.
