### ISSUE TITLE
Process is killed but evm status still running

### ISSUE THREAD

**Issue by hugo53** [duydo/evm#4]
Hi @duydo , 
First of all, I just want to say thank you for this very useful tool. 

I have a problem with evm and glad to see how we can fix it. Said, by a chance, I killed elastic process by ```kill -9 2539```, for example. However, ```evm status``` still shows that ```elastic is running```, so I cannot stop by ```evm stop```, like belows:

```
PC-5:zz$ ps | grep elastic
 2962 ttys006    0:00.00 grep elastic
PC-5:zz $ evm status
Elasticsearch 5.3.2 is running.
PC-5:zz $ evm stop
==> Stopping Elasticsearch
/usr/local/bin/evm: line 227: kill: (2593) - No such process
Could not stop Elasticsearch.
```
Any suggestion would be appreciated!
Thank you!

**Comment by duydo** [comment]
@hugo53 Thanks for reporting this issue. I've just committed the fix, you now can re-install the tool.

**Comment by hugo53** [comment]
@duydo Thanks for quick fix. Let me try!
