### ISSUE TITLE
Where is /etc/default/elasticsearch file

### ISSUE THREAD

**Issue by lporras** [duydo/evm#7]
Hi guys,

I have a question, I need to configure the option MAX_LOCKED_MEMORY commonly located in /etc/default/elasticsearch

but Since I'm using EVM I don't have that directory, where is it located?

**Comment by duydo** [comment]
Hi @lporras,
The `evm` uses  `.tar.gz` packages to install Elasticsearch so there is no `/etc/default/elasticsearch` config file, this config file is only available when you install RPM or Debian packages.

Install Elasticsearch with `evm`, these settings can be configured:

- temporarily with `ulimit`
- permanently in `/etc/security/limits.conf`

And other Elasticsearch configs can be found under `~/.evm/elasticsearch/`

For your more information https://www.elastic.co/guide/en/elasticsearch/reference/master/setting-system-settings.html

P.S: you should keep in mind: the `evm` was created for development environment only.
